### ISSUE TITLE
Customer sees prices from other customer groups

### ISSUE THREAD

**Issue by Omitri** [krakencommerce/magento2-module-customer-group-fixed-price#1]
Hi,

First of all, thank you for the plugin, it made my day. I have a webshop with multiple customer groups created by an API, so that I can set up different prices per customer. However, when I include all customer groups in the config and I log in with a specific customer, I also see prices of other customer groups. I managed to change this behaviour by changing Config.php line 175:

`in_array($tierPrice['cust_group'], $this->getCustomerGroups()) to $tierPrice['cust_group'] == $this->getCurrentCustomerGroup()`

**Comment by erikhansen** [comment]
@Omitri Thanks for this issue report! I've [fixed this issue in this commit](https://github.com/krakencommerce/magento2-module-customer-group-fixed-price/commit/23bd39e31b183cf8f66bb5662b62755077f3aa41). I didn't experience this issue during testing/development as I only had a single Customer Group selected in `STORES > Configuration > KRAKEN > General > Customer Group Pricing > Customer Groups`.

**Comment by Omitri** [comment]
@erikhansen You're welcome, thank you for this feature! I just realised it should be a combination of both conditions, because now all customer groups are taken into account, even the ones not selected in the admin:

`in_array($tierPrice['cust_group'], $this->getCustomerGroups()) && $tierPrice['cust_group'] == $this->getCurrentCustomerGroup()`

**Comment by erikhansen** [comment]
@Omitri Oh, good catch. I just tested your suggested change added [a commit](https://github.com/krakencommerce/magento2-module-customer-group-fixed-price/commit/ab22598d952cea3e5728ae257683ac314c9f8aa3) to address this.
