### ISSUE TITLE
Infinite loop detected when creating order

### ISSUE THREAD

**Issue by Omitri** [krakencommerce/magento2-module-customer-group-fixed-price#2]
Hello,

I'm using Magento 2.3.4 and experience the following error when I activate the plugin and I want to checkout an order, when clicking the payment button on the last step of the checkout. When I deactivate the plugin, things seem to work as normal. There is a similar issue reported for 3th party plugins (https://github.com/magento/magento2/issues/26786). Would you mind checking it out? Thanks!

The error:

`[2020-04-15 19:54:49] main.CRITICAL: Report ID: webapi-5e97668952603; Message: Infinite loop detected, review the trace for the looping path {"exception":"[object] (Exception(code: 0): Report ID: webapi-5e97668952603; Message: Infinite loop detected, review the trace for the looping path at /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Webapi/ErrorProcessor.php:208, LogicException(code: 0): Infinite loop detected, review the trace for the looping path at /opt/bitnami/apps/magento/htdocs/vendor/magento/module-checkout/Model/Session.php:241)"} []`

**Comment by erikhansen** [comment]
@Omitri Any chance you can resolve this issue and submit a PR? I don't have any 2.3.4 sites using this extension so I won't be able to fix it for now.

**Comment by Omitri** [comment]
@erikhansen I gave it a change but my knowledge of Magento 2 is limited. I'll await the 2.3.5 update which comes next week to see if it solves the problem.

**Comment by Omitri** [comment]
Hi @erikhansen, I updated to 2.3.5 and the problem still exists. Any chance you'd like to take a look at it? I have a testserver available with the most recent version.

**Comment by AngelVazquezArroyo** [comment]
The same here, I have troubles since I have updated from 2.3.3 :(

**Comment by erikhansen** [comment]
@Omitri It will be a while before I upgrade my client's site to 2.3.5 (they are on 2.3.4-p2), so unfortunately I won't be able to fix it until then.

**Comment by erikhansen** [comment]
@Omitri I finally made time to look at this. I've pushed up a commit that fixes this issue.

**Comment by Omitri** [comment]
@erikhansen thank you!
