### ISSUE TITLE
Higher price is not visible in product list

### ISSUE THREAD

**Issue by Omitri** [krakencommerce/magento2-module-customer-group-fixed-price#3]
Hi @erikhansen, I noticed that the plugin doesn't seem to do the job in the product listing. On the detail page it does work. Would you mind to take another look? It seems to be a new problem since Magento 2.3.5. Thanks.

**Comment by erikhansen** [comment]
@Omitri I was able to reproduce that issue. However my merchant has no need of this functionality, and I'm not able to spend time on it. So I've added this issue to a new ["Known Issues" section of the readme](https://github.com/krakencommerce/magento2-module-customer-group-fixed-price#known-issues).

**Comment by Omitri** [comment]
@erikhansen, thanks for the info!

**Comment by Omitri** [comment]
Hi @erikhansen, I took another look at this issue and found out that the tier price array was empty in Config.php, function getCustomerGroupFixedPrice, line 174 returns an empty array when the product list is loaded. I could fix it in a rather dirty way by loading the product through the ProductRepositoryInterface, then the array is filled when called upon.

**Comment by KhaledBinAmir** [comment]
Does Magento 2.4.1 show higher tier prices?

**Comment by erikhansen** [comment]
@hiimkhaled We've not tested this on 2.4.x, so not sure yet.

**Comment by KhaledBinAmir** [comment]
Just tested, it is not working on 2.4.x

**Comment by erikhansen** [comment]
@hiimkhaled Ok. I'll let you know if/when we upgrade this extension to support 2.4. In the meantime, if you fix it yourself, a pull request would be welcome.

**Comment by erikhansen** [comment]
Fixed in PR #4, so closing
